import { boundaries_coarse_name_zoom } from "../zoom";

export const boundaries_coarse_name = [
  {
    id: "boundaries-coarse-name-district",
    type: "symbol",
    source: "boundaries_coarse_name",
    "source-layer": "boundaries_coarse_name",
    filter: ["all", ["==", "admin_level", "6"], ["has", "name"]],
    minzoom: boundaries_coarse_name_zoom.min + 4,
    maxzoom: boundaries_coarse_name_zoom.max,
    layout: {
      "icon-image": "region",
      "icon-size": 1.1,
      "icon-anchor": "center",
      "icon-allow-overlap": false,
      "text-field": ["get", "name"],
      "text-size": [
        "interpolate",
        ["linear"],
        ["zoom"],
        boundaries_coarse_name_zoom.min + 4,
        15,
        boundaries_coarse_name_zoom.max,
        18,
      ],
      "symbol-placement": "point",
      "text-justify": "center",
      "text-offset": [0, -1.9],
      "text-font": ["Noto Sans Regular"],
    },
    paint: {
      "text-color": "#000000",
      "text-halo-color": "rgba(255, 250, 250, 0.8)",
      "text-halo-width": 2.5,
      "text-opacity": [
        "interpolate",
        ["linear"],
        ["zoom"],
        0,
        0,
        boundaries_coarse_name_zoom.min + 4,
        1,
        boundaries_coarse_name_zoom.min + 4 + 0.01,
        1,
        boundaries_coarse_name_zoom.max,
        1,
      ],
    },
  },
];
