import { boundaries_coarse_zoom, INC } from "../zoom";

export const boundaries_coarse = [
  {
    id: "boundaries-low-zoom-fill",
    type: "fill",
    source: "boundaries_coarse",
    "source-layer": "boundaries_coarse",
    filter: [
      "all",
      ["in", "admin_level", "3", "4"],
      ["has", "name"],
      ["!=", "name", "Province d'Antsiranana"]  // Exclude Antsiranana from fill
    ],
    minzoom: 4,
    maxzoom: 12,
    paint: {
      "fill-color": "#F6F5F5",
      "fill-opacity": 1,
    },
  },
  {
  id: "boundaries-coarse-line-district",
  type: "line",
  source: "boundaries_coarse",
  "source-layer": "boundaries_coarse",
  filter: ["all", ["==", "admin_level", "4"], ["has", "name"]],
  paint: {
    "line-color": "rgba(0, 0, 0 ,1)",
    "line-width": [
      "interpolate",
      ["linear"],
      ["zoom"],
      0,
      0,
      boundaries_coarse_zoom.min,
      0.5,
      boundaries_coarse_zoom.min + INC,
      1,
      boundaries_coarse_zoom.max,
      0.5,
    ],
    "line-dasharray": [.5, 4],
  },
  },
  // {
  //   id: "boundaries-low-zoom-line",
  //   type: "line",
  //   source: "boundaries_coarse",
  //   "source-layer": "boundaries_coarse",
  //   filter: ["all", ["in", "admin_level", "3", "4"], ["has", "name"]],
  //   minzoom: 4,
  //   maxzoom: 12,
  //   paint: {
  //     "line-color": "rgba(0, 0, 0, 1)",
  //     "line-width": [
  //       "interpolate",
  //       ["linear"],
  //       ["zoom"],
  //       4,
  //       0.5,
  //       8,
  //       1,
  //       11,
  //       1.5,
  //     ],
  //     "line-dasharray": [0.5, 4],
  //   },
  // },

  // HIGH ZOOM (12+): Show all levels
  // {
  //   id: "boundaries-high-zoom-fill-major",
  //   type: "fill",
  //   source: "boundaries_coarse",
  //   "source-layer": "boundaries_coarse",
  //   filter: [
  //     "all",
  //     ["in", "admin_level", "3", "4", "5"],
  //     ["has", "name"],
  //     ["!=", "name", "Province d'Antsiranana"]  // Exclude Antsiranana from fill
  //   ],
  //   minzoom: 12,
  //   paint: {
  //     "fill-color": "#053174ff",
  //     "fill-opacity": 1,
  //   },
  // },
  // {
  //   id: "boundaries-high-zoom-line-major",
  //   type: "line",
  //   source: "boundaries_coarse",
  //   "source-layer": "boundaries_coarse",
  //   filter: ["all", ["in", "admin_level", "3", "4", "5"], ["has", "name"]],
  //   minzoom: 12,
  //   paint: {
  //     "line-color": "rgba(0, 0, 0, 1)",
  //     "line-width": [
  //       "interpolate",
  //       ["linear"],
  //       ["zoom"],
  //       12,
  //       1.5,
  //       16,
  //       2,
  //       20,
  //       2.5,
  //     ],
  //     "line-dasharray": [0.5, 4],
  //   },
  // },
  {
    id: "boundaries-high-zoom-fill-districts",
    type: "fill",
    source: "boundaries_coarse",
    "source-layer": "boundaries_coarse",
    filter: ["all", ["==", "admin_level", "6"], ["has", "name"]],
    minzoom: 12,
    paint: {
      "fill-color": "#F6F5F5",
      "fill-opacity": 1,
    },
  },
  {
    id: "boundaries-high-zoom-line-districts",
    type: "line",
    source: "boundaries_coarse",
    "source-layer": "boundaries_coarse",
    filter: ["all", ["==", "admin_level", "6"], ["has", "name"]],
    minzoom: 12,
    paint: {
      "line-color": "rgba(0, 0, 0, 0.7)",
      "line-width": [
        "interpolate",
        ["linear"],
        ["zoom"],
        12,
        0.3,
        16,
        1,
        20,
        1.2,
      ],
      "line-dasharray": [0.5, 3],
    },
  },
];