import { landuse_zoom } from "../zoom"

const colors = {
  forest: "#a1eebdbb",
  grass: "#A1EEBD",
  farmland: "#FFF9D2",
  orchard: "#ffc2c2ff",
  cemetery: "#E0E8E0",
  military: "#F3E8E8",
  education: "#F5F0E0",
  rock: "#E8E0D8",
  quarry: "#DED8D0",
  residential: "#C3F1D5",
  commercial: "#C3F1D5",
  industrial: "#C3F1D5",
  retail: "#C3F1D5",
}

export const landuse = [
  {
    id: "forest-wood-fill",
    type: "fill",
    "source-layer": "landuse",
    minzoom: 11,
    maxzoom: landuse_zoom.max,
    filter: ["any", ["==", "natural", "wood"], ["==", "landuse", "forest"]],
    paint: {
      "fill-color": colors.forest,
      "fill-opacity": ["interpolate", ["linear"], ["zoom"], 2, 0.3, 6, 0.6, 10, 0.8, 15, 0.9],
    },
  },
  // {
  //   id: "farmland-fill",
  //   type: "fill",
  //   "source-layer": "landuse",
  //   minzoom: 11,
  //   maxzoom: landuse_zoom.max,
  //   filter: ["any", ["==", "landuse", "farmland"], ["==", "landuse", "paddy"], ["==", "landuse", "orchard"], ["==", "landuse", "vineyard"], ["==", "landuse", "plant_nursery"]],
  //   paint: {
  //     "fill-color": ["match", ["get", "landuse"], "orchard", colors.orchard, "vineyard", colors.orchard, colors.farmland],
  //     "fill-opacity": ["interpolate", ["linear"], ["zoom"], 8, 0.4, 12, 0.7, 16, 0.85],
  //   },
  // },
  {
    id: "grass-meadow-fill",
    type: "fill",
    "source-layer": "landuse",
    minzoom: 13,
    maxzoom: landuse_zoom.max,
    filter: ["any", ["==", "landuse", "grass"], ["==", "landuse", "meadow"], ["==", "natural", "grassland"], ["==", "landuse", "village_green"], ["==", "landuse", "recreation_ground"]],
    paint: {
      "fill-color": colors.grass,
      "fill-opacity": 0.6,
    },
  },
  {
    id: "scrub-fill",
    type: "fill",
    "source-layer": "landuse",
    minzoom: 14,
    maxzoom: landuse_zoom.max,
    filter: ["any", ["==", "natural", "scrub"], ["==", "landuse", "scrub"]],
    paint: {
      "fill-color": "#D5E5D0",
      "fill-opacity": 0.5,
    },
  },
  {
    id: "residential-fill",
    type: "fill",
    "source-layer": "landuse",
    minzoom: 14,
    maxzoom: landuse_zoom.max,
    filter: ["==", "landuse", "residential"],
    paint: {
      "fill-color": colors.residential,
      "fill-opacity": ["interpolate", ["linear"], ["zoom"], 10, 0.3, 13, 0.6, 16, 0.8],
    },
  },
  {
    id: "commercial-retail-fill",
    type: "fill",
    "source-layer": "landuse",
    minzoom: 14,
    maxzoom: landuse_zoom.max,
    filter: ["any", ["==", "landuse", "commercial"], ["==", "landuse", "retail"]],
    paint: {
      "fill-color": ["match", ["get", "landuse"], "retail", colors.retail, colors.commercial],
      "fill-opacity": 0.7,
    },
  },
  {
    id: "industrial-fill",
    type: "fill",
    "source-layer": "landuse",
    minzoom: 14,
    maxzoom: landuse_zoom.max,
    filter: ["any", ["==", "landuse", "industrial"], ["==", "landuse", "railway"], ["==", "landuse", "harbour"], ["==", "landuse", "quarry"]],
    paint: {
      "fill-color": ["match", ["get", "landuse"], "quarry", colors.quarry, colors.industrial],
      "fill-opacity": 0.6,
    },
  },
  {
    id: "education-fill",
    type: "fill",
    "source-layer": "landuse",
    minzoom: 13,
    maxzoom: landuse_zoom.max,
    filter: ["any", ["==", "landuse", "education"], ["==", "landuse", "school"]],
    paint: {
      "fill-color": colors.education,
      "fill-opacity": 0.7,
    },
  },
  {
    id: "cemetery-fill",
    type: "fill",
    "source-layer": "landuse",
    minzoom: 13,
    maxzoom: landuse_zoom.max,
    filter: ["any", ["==", "landuse", "cemetery"], ["==", "landuse", "churchyard"]],
    paint: {
      "fill-color": colors.cemetery,
      "fill-opacity": 0.6,
    },
  },
  {
    id: "military-fill",
    type: "fill",
    "source-layer": "landuse",
    minzoom: 13,
    maxzoom: landuse_zoom.max,
    filter: ["==", "landuse", "military"],
    paint: {
      "fill-color": colors.military,
      "fill-opacity": 0.4,
    },
  },
  {
    id: "bare-rock-fill",
    type: "fill",
    "source-layer": "landuse",
    minzoom: 14,
    maxzoom: landuse_zoom.max,
    filter: ["any", ["==", "natural", "bare_rock"], ["==", "natural", "rock"]],
    paint: {
      "fill-color": colors.rock,
      "fill-opacity": 0.5,
    },
  },
  // {
  //   id: "landuse-outline",
  //   type: "line",
  //   "source-layer": "landuse",
  //   minzoom: 14,
  //   maxzoom: landuse_zoom.max,
  //   filter: ["any", ["==", "landuse", "forest"], ["==", "landuse", "residential"], ["==", "landuse", "commercial"], ["==", "landuse", "industrial"]],
  //   paint: {
  //     "line-color": ["match", ["get", "landuse"], "forest", "#A8FFA0", "residential", "#D0D0D0", "commercial", "#D8D0C8", "industrial", "#C8C8CB", "#CCCCCC"],
  //     "line-width": ["interpolate", ["linear"], ["zoom"], 14, 0.5, 18, 1],
  //     "line-opacity": 0.4,
  //   },
  // },
]