const INC = 2 ; 
export const locations = [
  {
    id: "locations-symbol",
    type: "symbol",
    source: "locations",
    "source-layer": "locations",
    minzoom: 4,
    maxzoom: 20,
    filter: ["has", "name"],
    layout: {
      "icon-image": "gp_889",
      "icon-size": 1.6,
    //   "icon-anchor": "top",
      "icon-allow-overlap": false,
      "text-field": ["upcase", ["get", "name"]],
      "text-justify": "center",
      "text-font": ["Open Sans Regular", "Arial Unicode MS Regular"],
      "text-size": [
        "interpolate",
        ["linear"],
        ["zoom"],
        0,
        0,
        4,
        11,
        20 + INC,
        12,
      ],
      "symbol-placement": "point",
        "text-anchor": "right",
        "text-offset": [-2, 0],
      "symbol-spacing": 500,
      "text-allow-overlap": false,
    },
    paint: {
      "text-color": "#5E53EE",
      "text-halo-color": "rgba(255, 250, 250, 0.8)", // Dark, semi-transparent
      "text-halo-width": 2.5,
      "text-halo-blur": 1,
      "text-opacity": [
        "interpolate",
        ["linear"],
        ["zoom"],
        0,
        1,
        4,
        1,
        4+ 0.01,
        1,
      ],
    },
  },
]