import { boundaries_coarse_zoom } from "../zoom"

export const regions = [
  // {
  //   id: "regions-fill",
  //   type: "fill",
  //   source: "boundaries_coarse",
  //   "source-layer": "boundaries_coarse",
  //   minzoom: boundaries_coarse_zoom.min,
  //   maxzoom: boundaries_coarse_zoom.max,
  //   paint: {
  //     "fill-color": [
  //       "match",
  //       ["get", "name"],
  //       "Analamanga",
  //       "#F5F0E5",
  //       "Vakinankaratra",
  //       "#F5F0E5",
  //       "Itasy",
  //       "#F5F0E5",
  //       "Bongolava",
  //       "#F5F0E5",
  //       "Menabe",
  //       "rgba(174, 236, 188, 1)",
  //       "Atsimo-Andrefana",
  //       "#F5F0E5",
  //       "Anosy",
  //       "#F5F0E5",
  //       "Androy",
  //       "rgba(245,240,228,1)",
  //       "Atsimo-Atsinanana",
  //       "rgba(174, 236, 188, 1)",
  //       "Ihorombe",
  //       "#F5F0E4",
  //       "Amoron'i Mania",
  //       "#F5F0E5",
  //       "Matsiatra Ambony",
  //       "#F5F0E5",
  //       "Fitovinany",
  //       "rgba(174, 236, 188, 1)",
  //       "Vatovavy",
  //       "rgba(174, 236, 188, 1)",
  //       "Atsinanana",
  //       "rgba(174, 236, 188, 1)",
  //       "Alaotra-Mangoro",
  //       "rgba(174, 236, 188, 1)",
  //       "Analanjirofo",
  //       "rgba(174, 236, 188, 1)",
  //       "Betsiboka",
  //       "rgba(245,240,228,1)",
  //       "Melaky",
  //       "#F5F0E5",
  //       "Boeny",
  //       "rgba(245,240,228,1)",
  //       "Ambatosoa",
  //       "rgba(174, 236, 188, 1)",
  //       "Sofia",
  //       "#F5F0E5",
  //       "Sava",
  //       "rgba(174, 236, 188, 1)",
  //       "Diana",
  //       "rgba(174, 236, 188, 1)",
  //       /* default */ "rgba(0,0,0,0)",
  //     ],
  //     "fill-opacity": [
  //       "interpolate",
  //       ["linear"],
  //       ["zoom"],
  //       0,
  //       0,
  //       boundaries_coarse_zoom.min,
  //       1,
  //       boundaries_coarse_zoom.min + 0.01,
  //       1,
  //       boundaries_coarse_zoom.max,
  //       1,
  //     ],
  //   },
  // },
]
