import { boundaries_coarse_name_zoom } from "../zoom"

export const regions = [
  {
    id: "boundaries-coarse-name-region",
    type: "symbol",
    source: "boundaries_coarse_name",
    "source-layer": "boundaries_coarse_name",
    filter: ["all", ["==", "admin_level", "4"], ["has", "name"]],
    minzoom: boundaries_coarse_name_zoom.min,
    maxzoom: boundaries_coarse_name_zoom.max - 3,
    layout: {
      "icon-image": "region",
      "icon-size": [
        "interpolate",
        ["linear"],
        ["zoom"],
        boundaries_coarse_name_zoom.min + 2,
        0.8,
      ],
      "icon-anchor": "bottom",
      "icon-allow-overlap": false,
      "text-field": ["get", "name"],
      "text-size": [
        "interpolate",
        ["linear"],
        ["zoom"],
        boundaries_coarse_name_zoom.min,
        15,
        boundaries_coarse_name_zoom.max - 3,
        18,
      ],
      "symbol-placement": "point",
      "text-justify": "center",
      "text-anchor": "bottom",
      "text-offset": [0, -1.9],
      "text-font": ["Noto Sans Regular"],
    },
    paint: {
      "text-color": "#000000",
      "text-halo-color": "rgba(255, 250, 250, 0.8)", // Dark, semi-transparent
      "text-halo-width": 2.5,
      "text-opacity": [
        "interpolate",
        ["linear"],
        ["zoom"],
        0,
        1,
        boundaries_coarse_name_zoom.min,
        1,
        boundaries_coarse_name_zoom.min + 0.01,
        1,
        boundaries_coarse_name_zoom.max - 3,
        0.5,
      ],
    },
  },

  // {
  //   id: "regions-fill",
  //   type: "fill",
  //   source: "boundaries_coarse",
  //   "source-layer": "boundaries_coarse",
  //   minzoom: boundaries_coarse_zoom.min,
  //   maxzoom: boundaries_coarse_zoom.max,
  //   paint: {
  //     "fill-color": [
  //       "match",
  //       ["get", "name"],
  //       "Analamanga",
  //       "#F5F0E5",
  //       "Vakinankaratra",
  //       "#F5F0E5",
  //       "Itasy",
  //       "#F5F0E5",
  //       "Bongolava",
  //       "#F5F0E5",
  //       "Menabe",
  //       "rgba(174, 236, 188, 1)",
  //       "Atsimo-Andrefana",
  //       "#F5F0E5",
  //       "Anosy",
  //       "#F5F0E5",
  //       "Androy",
  //       "rgba(245,240,228,1)",
  //       "Atsimo-Atsinanana",
  //       "rgba(174, 236, 188, 1)",
  //       "Ihorombe",
  //       "#F5F0E4",
  //       "Amoron'i Mania",
  //       "#F5F0E5",
  //       "Matsiatra Ambony",
  //       "#F5F0E5",
  //       "Fitovinany",
  //       "rgba(174, 236, 188, 1)",
  //       "Vatovavy",
  //       "rgba(174, 236, 188, 1)",
  //       "Atsinanana",
  //       "rgba(174, 236, 188, 1)",
  //       "Alaotra-Mangoro",
  //       "rgba(174, 236, 188, 1)",
  //       "Analanjirofo",
  //       "rgba(174, 236, 188, 1)",
  //       "Betsiboka",
  //       "rgba(245,240,228,1)",
  //       "Melaky",
  //       "#F5F0E5",
  //       "Boeny",
  //       "rgba(245,240,228,1)",
  //       "Ambatosoa",
  //       "rgba(174, 236, 188, 1)",
  //       "Sofia",
  //       "#F5F0E5",
  //       "Sava",
  //       "rgba(174, 236, 188, 1)",
  //       "Diana",
  //       "rgba(174, 236, 188, 1)",
  //       /* default */ "rgba(0,0,0,0)",
  //     ],
  //     "fill-opacity": [
  //       "interpolate",
  //       ["linear"],
  //       ["zoom"],
  //       0,
  //       0,
  //       boundaries_coarse_zoom.min,
  //       1,
  //       boundaries_coarse_zoom.min + 0.01,
  //       1,
  //       boundaries_coarse_zoom.max,
  //       1,
  //     ],
  //   },
  // },
]
