import { INC, roads_low_zoom } from "../zoom";

export const roads_low = [
  {
    id: "roads-low-primary",
    type: "line",
    source: "roads_low",
    "source-layer": "roads_low",
    minzoom: roads_low_zoom.min,
    maxzoom: roads_low_zoom.max,
    filter: ["in", ["get", "highway"], ["literal", ["motorway", "trunk", "primary"]]],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-color": "rgba(139, 165, 193, 1)",
      "line-width": [
        "interpolate",
        ["linear"],
        ["zoom"],
        roads_low_zoom.min, 0.5,
        roads_low_zoom.min + INC, 1.5,
        roads_low_zoom.min + INC * 2, 3.5,
        roads_low_zoom.min + INC * 3, 4.0,
        roads_low_zoom.max - 3, 35,
      ],
    },
  },
];  // {
  //   id: "roads-low-ref-symbol-RN",
  //   type: "symbol",
  //   source: "roads_low",
  //   "source-layer": "roads_low",
  //   minzoom: roads_low_zoom.min,
  //   maxzoom: roads_low_zoom.max,
  //   filter: ["has", "ref"],
  //   layout: {
  //     "text-field": ["get", "ref"],
  //     "text-size": [
  //       "interpolate",
  //       ["linear"],
  //       ["zoom"],
  //       roads_low_zoom.min,
  //       9,
  //       roads_low_zoom.min + INC,
  //       11,
  //       roads_low_zoom.min + INC * 2,
  //       12,
  //       roads_low_zoom.max,
  //       13,
  //     ],
  //     "symbol-placement": "line",
  //     "symbol-spacing": 300,
  //     "text-font": ["Noto Sans Bold"],
  //     "text-rotation-alignment": "viewport",
  //     "text-pitch-alignment": "viewport",
  //     "text-keep-upright": true,
  //     "text-allow-overlap": false,
  //     "text-ignore-placement": false,
  //   },
  //   paint: {
  //     "text-color": "#ffffff",
  //     "text-halo-color": "#8ba5c1",
  //     "text-halo-width": 1.5,
  //   },
  // },
